// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Ilia9531/microservices-warehouse/order/internal/model"
)

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

type InventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClient) EXPECT() *InventoryClient_Expecter {
	return &InventoryClient_Expecter{mock: &_m.Mock}
}

// ListPartsByUUIDs provides a mock function with given fields: ctx, uuids
func (_m *InventoryClient) ListPartsByUUIDs(ctx context.Context, uuids []string) ([]*model.Part, error) {
	ret := _m.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for ListPartsByUUIDs")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*model.Part, error)); ok {
		return rf(ctx, uuids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.Part); ok {
		r0 = rf(ctx, uuids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, uuids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryClient_ListPartsByUUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPartsByUUIDs'
type InventoryClient_ListPartsByUUIDs_Call struct {
	*mock.Call
}

// ListPartsByUUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []string
func (_e *InventoryClient_Expecter) ListPartsByUUIDs(ctx interface{}, uuids interface{}) *InventoryClient_ListPartsByUUIDs_Call {
	return &InventoryClient_ListPartsByUUIDs_Call{Call: _e.mock.On("ListPartsByUUIDs", ctx, uuids)}
}

func (_c *InventoryClient_ListPartsByUUIDs_Call) Run(run func(ctx context.Context, uuids []string)) *InventoryClient_ListPartsByUUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *InventoryClient_ListPartsByUUIDs_Call) Return(_a0 []*model.Part, _a1 error) *InventoryClient_ListPartsByUUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryClient_ListPartsByUUIDs_Call) RunAndReturn(run func(context.Context, []string) ([]*model.Part, error)) *InventoryClient_ListPartsByUUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
