// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// APIV1OrdersOrderUUIDCancelPostNoContent is response for APIV1OrdersOrderUUIDCancelPost operation.
type APIV1OrdersOrderUUIDCancelPostNoContent struct{}

func (*APIV1OrdersOrderUUIDCancelPostNoContent) aPIV1OrdersOrderUUIDCancelPostRes() {}

// APIV1OrdersOrderUUIDCancelPostNotFound is response for APIV1OrdersOrderUUIDCancelPost operation.
type APIV1OrdersOrderUUIDCancelPostNotFound struct{}

func (*APIV1OrdersOrderUUIDCancelPostNotFound) aPIV1OrdersOrderUUIDCancelPostRes() {}

// APIV1OrdersOrderUUIDGetNotFound is response for APIV1OrdersOrderUUIDGet operation.
type APIV1OrdersOrderUUIDGetNotFound struct{}

func (*APIV1OrdersOrderUUIDGetNotFound) aPIV1OrdersOrderUUIDGetRes() {}

// APIV1OrdersOrderUUIDPayPostNotFound is response for APIV1OrdersOrderUUIDPayPost operation.
type APIV1OrdersOrderUUIDPayPostNotFound struct{}

func (*APIV1OrdersOrderUUIDPayPostNotFound) aPIV1OrdersOrderUUIDPayPostRes() {}

// APIV1OrdersPostNotFound is response for APIV1OrdersPost operation.
type APIV1OrdersPostNotFound struct{}

func (*APIV1OrdersPostNotFound) aPIV1OrdersPostRes() {}

// Ref: #/components/schemas/CreateOrderRequest
type CreateOrderRequest struct {
	UserUUID  string   `json:"user_uuid"`
	PartUuids []string `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []string {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []string) {
	s.PartUuids = val
}

// Ref: #/components/schemas/CreateOrderResponse
type CreateOrderResponse struct {
	OrderUUID  OptUUID    `json:"order_uuid"`
	TotalPrice OptFloat64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() OptUUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() OptFloat64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val OptUUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val OptFloat64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) aPIV1OrdersPostRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Code    OptString `json:"code"`
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() OptString {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val OptString) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val OptString) {
	s.Message = val
}

func (*Error) aPIV1OrdersOrderUUIDCancelPostRes() {}
func (*Error) aPIV1OrdersOrderUUIDGetRes()        {}
func (*Error) aPIV1OrdersOrderUUIDPayPostRes()    {}
func (*Error) aPIV1OrdersPostRes()                {}

// Ref: #/components/schemas/GetOrderResponse
type GetOrderResponse struct {
	OrderUUID       string                              `json:"order_uuid"`
	UserUUID        string                              `json:"user_uuid"`
	PartUuids       []string                            `json:"part_uuids"`
	TotalPrice      float64                             `json:"total_price"`
	TransactionUUID OptNilString                        `json:"transaction_uuid"`
	PaymentMethod   OptNilGetOrderResponsePaymentMethod `json:"payment_method"`
	Status          GetOrderResponseStatus              `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *GetOrderResponse) GetOrderUUID() string {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *GetOrderResponse) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *GetOrderResponse) GetPartUuids() []string {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *GetOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *GetOrderResponse) GetTransactionUUID() OptNilString {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *GetOrderResponse) GetPaymentMethod() OptNilGetOrderResponsePaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *GetOrderResponse) GetStatus() GetOrderResponseStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *GetOrderResponse) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *GetOrderResponse) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *GetOrderResponse) SetPartUuids(val []string) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *GetOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *GetOrderResponse) SetTransactionUUID(val OptNilString) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *GetOrderResponse) SetPaymentMethod(val OptNilGetOrderResponsePaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *GetOrderResponse) SetStatus(val GetOrderResponseStatus) {
	s.Status = val
}

func (*GetOrderResponse) aPIV1OrdersOrderUUIDGetRes() {}

type GetOrderResponsePaymentMethod string

const (
	GetOrderResponsePaymentMethodCARD          GetOrderResponsePaymentMethod = "CARD"
	GetOrderResponsePaymentMethodSBP           GetOrderResponsePaymentMethod = "SBP"
	GetOrderResponsePaymentMethodCREDITCARD    GetOrderResponsePaymentMethod = "CREDIT_CARD"
	GetOrderResponsePaymentMethodINVESTORMONEY GetOrderResponsePaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all GetOrderResponsePaymentMethod values.
func (GetOrderResponsePaymentMethod) AllValues() []GetOrderResponsePaymentMethod {
	return []GetOrderResponsePaymentMethod{
		GetOrderResponsePaymentMethodCARD,
		GetOrderResponsePaymentMethodSBP,
		GetOrderResponsePaymentMethodCREDITCARD,
		GetOrderResponsePaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetOrderResponsePaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case GetOrderResponsePaymentMethodCARD:
		return []byte(s), nil
	case GetOrderResponsePaymentMethodSBP:
		return []byte(s), nil
	case GetOrderResponsePaymentMethodCREDITCARD:
		return []byte(s), nil
	case GetOrderResponsePaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetOrderResponsePaymentMethod) UnmarshalText(data []byte) error {
	switch GetOrderResponsePaymentMethod(data) {
	case GetOrderResponsePaymentMethodCARD:
		*s = GetOrderResponsePaymentMethodCARD
		return nil
	case GetOrderResponsePaymentMethodSBP:
		*s = GetOrderResponsePaymentMethodSBP
		return nil
	case GetOrderResponsePaymentMethodCREDITCARD:
		*s = GetOrderResponsePaymentMethodCREDITCARD
		return nil
	case GetOrderResponsePaymentMethodINVESTORMONEY:
		*s = GetOrderResponsePaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetOrderResponseStatus string

const (
	GetOrderResponseStatusPENDINGPAYMENT GetOrderResponseStatus = "PENDING_PAYMENT"
	GetOrderResponseStatusPAID           GetOrderResponseStatus = "PAID"
	GetOrderResponseStatusCANCELLED      GetOrderResponseStatus = "CANCELLED"
	GetOrderResponseStatusASSEMBLED      GetOrderResponseStatus = "ASSEMBLED"
)

// AllValues returns all GetOrderResponseStatus values.
func (GetOrderResponseStatus) AllValues() []GetOrderResponseStatus {
	return []GetOrderResponseStatus{
		GetOrderResponseStatusPENDINGPAYMENT,
		GetOrderResponseStatusPAID,
		GetOrderResponseStatusCANCELLED,
		GetOrderResponseStatusASSEMBLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetOrderResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case GetOrderResponseStatusPENDINGPAYMENT:
		return []byte(s), nil
	case GetOrderResponseStatusPAID:
		return []byte(s), nil
	case GetOrderResponseStatusCANCELLED:
		return []byte(s), nil
	case GetOrderResponseStatusASSEMBLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetOrderResponseStatus) UnmarshalText(data []byte) error {
	switch GetOrderResponseStatus(data) {
	case GetOrderResponseStatusPENDINGPAYMENT:
		*s = GetOrderResponseStatusPENDINGPAYMENT
		return nil
	case GetOrderResponseStatusPAID:
		*s = GetOrderResponseStatusPAID
		return nil
	case GetOrderResponseStatusCANCELLED:
		*s = GetOrderResponseStatusCANCELLED
		return nil
	case GetOrderResponseStatusASSEMBLED:
		*s = GetOrderResponseStatusASSEMBLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilGetOrderResponsePaymentMethod returns new OptNilGetOrderResponsePaymentMethod with value set to v.
func NewOptNilGetOrderResponsePaymentMethod(v GetOrderResponsePaymentMethod) OptNilGetOrderResponsePaymentMethod {
	return OptNilGetOrderResponsePaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptNilGetOrderResponsePaymentMethod is optional nullable GetOrderResponsePaymentMethod.
type OptNilGetOrderResponsePaymentMethod struct {
	Value GetOrderResponsePaymentMethod
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilGetOrderResponsePaymentMethod was set.
func (o OptNilGetOrderResponsePaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilGetOrderResponsePaymentMethod) Reset() {
	var v GetOrderResponsePaymentMethod
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilGetOrderResponsePaymentMethod) SetTo(v GetOrderResponsePaymentMethod) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilGetOrderResponsePaymentMethod) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilGetOrderResponsePaymentMethod) SetToNull() {
	o.Set = true
	o.Null = true
	var v GetOrderResponsePaymentMethod
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilGetOrderResponsePaymentMethod) Get() (v GetOrderResponsePaymentMethod, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilGetOrderResponsePaymentMethod) Or(d GetOrderResponsePaymentMethod) GetOrderResponsePaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PayOrderRequest
type PayOrderRequest struct {
	PaymentMethod PayOrderRequestPaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PayOrderRequestPaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PayOrderRequestPaymentMethod) {
	s.PaymentMethod = val
}

type PayOrderRequestPaymentMethod string

const (
	PayOrderRequestPaymentMethodCARD          PayOrderRequestPaymentMethod = "CARD"
	PayOrderRequestPaymentMethodSBP           PayOrderRequestPaymentMethod = "SBP"
	PayOrderRequestPaymentMethodCREDITCARD    PayOrderRequestPaymentMethod = "CREDIT_CARD"
	PayOrderRequestPaymentMethodINVESTORMONEY PayOrderRequestPaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PayOrderRequestPaymentMethod values.
func (PayOrderRequestPaymentMethod) AllValues() []PayOrderRequestPaymentMethod {
	return []PayOrderRequestPaymentMethod{
		PayOrderRequestPaymentMethodCARD,
		PayOrderRequestPaymentMethodSBP,
		PayOrderRequestPaymentMethodCREDITCARD,
		PayOrderRequestPaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PayOrderRequestPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PayOrderRequestPaymentMethodCARD:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodSBP:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodCREDITCARD:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PayOrderRequestPaymentMethod) UnmarshalText(data []byte) error {
	switch PayOrderRequestPaymentMethod(data) {
	case PayOrderRequestPaymentMethodCARD:
		*s = PayOrderRequestPaymentMethodCARD
		return nil
	case PayOrderRequestPaymentMethodSBP:
		*s = PayOrderRequestPaymentMethodSBP
		return nil
	case PayOrderRequestPaymentMethodCREDITCARD:
		*s = PayOrderRequestPaymentMethodCREDITCARD
		return nil
	case PayOrderRequestPaymentMethodINVESTORMONEY:
		*s = PayOrderRequestPaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/PayOrderResponse
type PayOrderResponse struct {
	TransactionUUID OptString `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() OptString {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val OptString) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) aPIV1OrdersOrderUUIDPayPostRes() {}
